apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"quant-invest-pg","namespace":"classic-dev"},"spec":{"externalIPs":["192.168.2.13"],"ports":[{"name":"postgresql","port":5432,"protocol":"TCP","targetPort":5432}],"selector":{"app.kubernetes.io/name":"kyd"},"sessionAffinity":"None","type":"ClusterIP"}}
  name: pg-quant-invest-externalip
  namespace: quant-invest
spec:
  externalIPs:
  - 192.168.2.20
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: pg-quant-invest
  sessionAffinity: None
  type: ClusterIP
