apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-quant-invest
  namespace: quant-invest
spec:
  storageClassName: nfs-client-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
