    create table stock.idx (
       id bigint not null,
        sec_id varchar(255),
        publish_date varchar(255),
        sec_short_name varchar(255),
        ticker varchar(255),
        index_type_cd varchar(255),
        index_type varchar(255),
        pub_org_cd float,
        porg_full_name varchar(255),
        base_date timestamp,
        base_point float,
        end_date date,
        index_group varchar(255),
        cons_type varchar(255),
        cons_mkt varchar(255),
        return_type varchar(255),
        w_method_cd varchar(255),
        update_time date,
        pub_name varchar(255),
        industry_id varchar(255),
        industry_name varchar(255),
        sort_id varchar(255),
        sort_name varchar(255),
        primary key (id)
    );
    create table stock.mkt_idx_day (
       id bigint not null,
        index_id varchar(255),
        ticker varchar(255),
        porg_full_name varchar(255),
        sec_short_name varchar(255),
        exchange_cd varchar(255),
        trade_date date,
        pre_close_index float,
        open_index float,
        lowest_index float,
        highest_index float,
        closee_index float,
        turnover_value float,
        turnover_vol float,
        chg float,
        chg_pct float,
        primary key (id)
    );    
    create table stock.fund (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        sec_short_name varchar(255),
        trade_abbr_name varchar(255),
        category varchar(255),
        operation_mode varchar(255),
        index_fund varchar(255),
        etf_lof varchar(255),
        is_qdii boolean,
        is_fof boolean,
        is_guar_fund boolean,
        guar_period float,
        guar_ratio float,
        exchange_cd varchar(255),
        list_status_cd varchar(255),
        manager_name varchar(255),
        status varchar(255),
        establish_date date,
        list_date date,
        delist_date date,
        expire_date date,
        management_company integer,
        management_full_name varchar(255),
        custodian integer,
        custodian_full_name varchar(255),
        invest_field varchar(2048),
        invest_target varchar(1024),
        perf_benchmark varchar(255),
        circulation_shares float,
        is_class integer,
        idx_id varchar(255),
        idx_ticker varchar(255),
        idx_short_name varchar(255),
        management_short_name varchar(255),
        custodian_short_name varchar(255),
        sec_full_name varchar(255),
        class_name varchar(255),
        primary key (id)
    );
    create table stock.fund_day (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        exchange_cd varchar(255),
        sec_short_name varchar(255),
        trade_date date,
        pre_close_price float,
        open_price float,
        highest_price float,
        lowest_price float,
        close_price float,
        chg float,
        chg_pct float,
        turnover_vol float,
        turnover_value float,
        discount float,
        discount_ratio float,
        circulation_shares float,
        accum_adj_factor float,
        primary key (id)
    )    
