    create table stock.equity (
        id bigint not null,
        sec_id varchar(255) not null,
        ticker varchar(255) ,
        exchange_cd varchar(255) ,
        list_sector_cd varchar(255) ,
        list_sector varchar(255),
        trans_curr_cd varchar(255) ,
        sec_short_name varchar(255) ,
        sec_full_name varchar(255) ,
        list_status_cd varchar(255) ,
        list_date date ,
        delist_date date ,
        equ_type_cd varchar(255) ,
        equ_type varchar(255) ,
        ex_country_cd varchar(255) ,
        party_id varchar(255) ,
        total_shares float ,
        non_rest_float_shares float ,
        non_rest_float_A float ,
        office_addr varchar(255) ,
        prime_operating varchar(255) ,
        end_date date ,
        tsh_equity float ,
        primary key (id)
    );
    create table stock.mkt_equ_day (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        sec_short_name varchar(255),
        exchange_cd varchar(255),
        trade_date date not null,
        pre_close_price float,
        act_pre_close_price float,
        open_price float,
        highest_price float,
        lowest_price float,
        close_price float,
        turnover_vol float,
        turnove_value float,
        deal_amount float,
        turnover_rate float,
        accum_adj_bf_factor float,
        neg_market_value float,
        market_value float,
        chg_pct float,
        pe float,
        pe1 float,
        pb float,
        is_open boolean,
        vwap float,
        accum_adj_af_factor float,
        primary key (id)
    );
    create table stock.equ_share (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        sec_short_name varchar(255),
        exchange_cd varchar(255),
        party_id varchar(255),
        change_date date,
        total_shares float,
        shares_a float,
        shares_b float,
        float_a float,
        nonrest_float_a float,
        float_b float,
        rest_shares float,
        nonrest_float_shares float,
        primary key (id)
    );
    create table stock.equity_industry (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        exchange_cd varchar(255),
        sec_short_name varchar(255),
        sec_full_name varchar(255),
        party_id varchar(255),
        industry_version_cd varchar(255),
        industry varchar(255),
        industry_id varchar(255),
        industry_symbol varchar(255),
        into_date date,
        out_date date,
        is_new boolean,
        industry_id1 varchar(255),
        industry_name1 varchar(255),
        industry_id2 varchar(255),
        industry_name2 varchar(255),
        industry_id3 varchar(255),
        industry_name3 varchar(255),
        industry_id4 varchar(255),
        industry_name4 varchar(255),
        equ_type varchar(255),
        primary key (id)
    );
    create table stock.sys_code (
       id bigint not null,
        code_type_id integer,
        value_cd varchar(255),
        value_name varchar(255),
        primary key (id)
    );    
    create table stock.trade_calendar (
       id bigint not null,
        exchange_cd varchar(255),
        calendar_date timestamp,
        is_open boolean,
        prev_trade_date timestamp,
        is_week_end boolean,
        is_month_end boolean,
        is_quarter_end boolean,
        is_year_end boolean,
        primary key (id)
    );    
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 6 INCREMENT BY 1;
-- CREATE SEQUENCE account_id_seq START WITH 6 INCREMENT BY 1;
