CREATE TABLE stock.fdmt_indi_ps_pit (
    id bigint NOT NULL,
    sec_id varchar(255),
    party_id varchar(255),
    ticker varchar(255),
    sec_short_name varchar(255),
    exchange_cd varchar(255),
    publish_date date,
    end_date date,
    eps float,
    act_pubtime timestamp,
    basic_eps float,
    diluted_eps float,
    n_asset_ps float,
    t_rev_ps float,
    rev_ps float,
    op_ps float,
    ebi_tps float,
    c_reser_ps float,
    s_reser_ps float,
    reser_Ps float,
    re_ps float,
    t_re_ps float,
    n_cf_oper_aps float,
    n_cin_cash_ps float,
    fcf_fps float,
    fcf_eps float,
    primary key (id)
);
CREATE SEQUENCE IF NOT EXISTS stock.fdmt_indi_ps_pit_id_seq START WITH 444323 INCREMENT BY 1;
