    create table stock.equity (
        id bigint not null,
        sec_id varchar(255) not null,
        ticker varchar(255) ,
        exchange_cd varchar(255) ,
        list_sector_cd varchar(255) ,
        list_sector varchar(255),
        trans_curr_cd varchar(255) ,
        sec_short_name varchar(255) ,
        sec_full_name varchar(255) ,
        list_status_cd varchar(255) ,
        list_date date ,
        delist_date date ,
        equ_type_cd varchar(255) ,
        equ_type varchar(255) ,
        ex_country_cd varchar(255) ,
        party_id varchar(255) ,
        total_shares float ,
        non_rest_float_shares float ,
        non_rest_float_A float ,
        office_addr varchar(255) ,
        prime_operating varchar(2048) ,
        end_date date ,
        tsh_equity float ,
        primary key (id)
    );
    create table stock.mkt_equ_day (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        sec_short_name varchar(255),
        exchange_cd varchar(255),
        trade_date date not null,
        pre_close_price float,
        act_pre_close_price float,
        open_price float,
        highest_price float,
        lowest_price float,
        close_price float,
        turnover_vol float,
        turnove_value float,
        deal_amount float,
        turnover_rate float,
        accum_adj_bf_factor float,
        neg_market_value float,
        market_value float,
        chg_pct float,
        pe float,
        pe1 float,
        pb float,
        is_open boolean,
        vwap float,
        accum_adj_af_factor float,
        primary key (id)
    );
    create table stock.equ_share (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        sec_short_name varchar(255),
        exchange_cd varchar(255),
        party_id varchar(255),
        change_date date,
        total_shares float,
        shares_a float,
        shares_b float,
        float_a float,
        nonrest_float_a float,
        float_b float,
        rest_shares float,
        nonrest_float_shares float,
        primary key (id)
    );
    create table stock.equity_industry (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        exchange_cd varchar(255),
        sec_short_name varchar(255),
        sec_full_name varchar(255),
        party_id varchar(255),
        industry_version_cd varchar(255),
        industry varchar(255),
        industry_id varchar(255),
        industry_symbol varchar(255),
        into_date date,
        out_date date,
        is_new boolean,
        industry_id1 varchar(255),
        industry_name1 varchar(255),
        industry_id2 varchar(255),
        industry_name2 varchar(255),
        industry_id3 varchar(255),
        industry_name3 varchar(255),
        industry_id4 varchar(255),
        industry_name4 varchar(255),
        equ_type varchar(255),
        primary key (id)
    );
    create table stock.sys_code (
       id bigint not null,
        code_type_id integer,
        value_cd varchar(255),
        value_name varchar(255),
        primary key (id)
    );    
    create table stock.trade_calendar (
       id bigint not null,
        exchange_cd varchar(255),
        calendar_date timestamp,
        is_open boolean,
        prev_trade_date timestamp,
        is_week_end boolean,
        is_month_end boolean,
        is_quarter_end boolean,
        is_year_end boolean,
        primary key (id)
    );
    create table stock.idx (
       id bigint not null,
        sec_id varchar(255),
        publish_date date,
        sec_short_name varchar(255),
        ticker varchar(255),
        index_type_cd varchar(255),
        index_type varchar(255),
        pub_org_cd float,
        porg_full_name varchar(255),
        base_date timestamp,
        base_point float,
        end_date date,
        index_group varchar(255),
        cons_type varchar(255),
        cons_mkt varchar(255),
        return_type varchar(255),
        w_method_cd varchar(255),
        update_time date,
        pub_name varchar(255),
        industry_id varchar(255),
        industry_name varchar(255),
        sort_id varchar(255),
        sort_name varchar(255),
        primary key (id)
    );
    create table stock.mkt_idx_day (
       id bigint not null,
        index_id varchar(255),
        ticker varchar(255),
        porg_full_name varchar(255),
        sec_short_name varchar(255),
        exchange_cd varchar(255),
        trade_date date,
        pre_close_index float,
        open_index float,
        lowest_index float,
        highest_index float,
        closee_index float,
        turnover_value float,
        turnover_vol float,
        chg float,
        chg_pct float,
        primary key (id)
    );    
    create table stock.fund (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        sec_short_name varchar(255),
        trade_abbr_name varchar(255),
        category varchar(255),
        operation_mode varchar(255),
        index_fund varchar(255),
        etf_lof varchar(255),
        is_qdii boolean,
        is_fof boolean,
        is_guar_fund boolean,
        guar_period float,
        guar_ratio float,
        exchange_cd varchar(255),
        list_status_cd varchar(255),
        manager_name varchar(255),
        status varchar(255),
        establish_date date,
        list_date date,
        delist_date date,
        expire_date date,
        management_company integer,
        management_full_name varchar(255),
        custodian integer,
        custodian_full_name varchar(255),
        invest_field varchar(3072),
        invest_target varchar(2048),
        perf_benchmark varchar(255),
        circulation_shares float,
        is_class integer,
        idx_id varchar(255),
        idx_ticker varchar(255),
        idx_short_name varchar(255),
        management_short_name varchar(255),
        custodian_short_name varchar(255),
        sec_full_name varchar(255),
        class_name varchar(255),
        primary key (id)
    );
    create table stock.fund_day (
       id bigint not null,
        sec_id varchar(255),
        ticker varchar(255),
        exchange_cd varchar(255),
        sec_short_name varchar(255),
        trade_date date,
        pre_close_price float,
        open_price float,
        highest_price float,
        lowest_price float,
        close_price float,
        chg float,
        chg_pct float,
        turnover_vol float,
        turnover_value float,
        discount float,
        discount_ratio float,
        circulation_shares float,
        accum_adj_factor float,
        primary key (id)
    );

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 6 INCREMENT BY 1;
-- CREATE SEQUENCE account_id_seq START WITH 6 INCREMENT BY 1;
